name: unique-comment
description: create or update a unique comment

runs:
    using: 'node20'
    main: './dist/index.js'

inputs:
    token:
        description: 'GitHub token'
        required: true
    owner:
        description: 'Repository owner'
        required: true
    repo:
        description: 'Repository name'
        required: true
    issue_number:
        description: 'Issue number'
        required: true
    body:
        description: 'Comment body'
        required: false
    uniqueIdentifier:
        description: 'Unique identifier for comment'
        required: false
        default: 'unique-comment'
