name: check pull request
run-name: check for pr #${{ github.event.pull_request.number }}
on:
    pull_request:
        types: [opened, synchronize, reopened]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello"
