name: check pull request
run-name: 'check pull request #${{ github.event.pull_request.number }}'
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
permissions:
    issues: write
    pull-requests: read
jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - name: init repo
              uses: actions/checkout@v4
            #   with:
            #       ref: ${{github.head_ref}}

            - name: node
              uses: actions/setup-node@v4
              with:
                  node-version: latest

            - name: pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 8
                  run_install: false

            - name: Get pnpm store directory
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ env.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Install dependencies
              run: pnpm install
    test1:
        runs-on: ubuntu-latest
        needs: init
        steps:
            - run: echo "this is test1"
