name: check pull request
run-name: check for pr #${{ github.event.pull_request.number }}
on:
    pull_request:
        types: [opened, synchronize, reopened]
    # TODO remove pull_request_review_comment
    pull_request_review_comment:
        types: [created]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello"
