name: check pull request
run-name: check for pr #${{ github.event.pull_request.number }}
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
    # TODO remove next type
    issue_comment:
        types: [created, edited]
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello"
