name: check pull request
run-name: 'check pull request #${{ github.event.pull_request.number || github.event.issue.number }}'
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
    # TODO remove next type
    issue_comment:
        types: [created, edited]
permissions:
    issues: write
    pull-requests: read
jobs:
    init-repo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "this is init-repo"
            - uses: actions/checkout@main
            # - uses: actions/setup-node@main
            #   with:
            #       node-version: latest
            - run: echo "base_ref is ${{github.base_ref}}"
            - run: echo "head_ref is ${{github.head_ref}}"
    test1:
        runs-on: ubuntu-latest
        needs: init-repo
        steps:
            - run: echo "this is test1"
