name: check pull request
run-name: 'check pull request #${{ github.event.pull_request.number }}'
on:
    pull_request:
        # TODO remove edited
        types: [opened, edited, synchronize, reopened]
permissions:
    issues: write
    pull-requests: write
jobs:
    replyChecking:
        name: reply checking
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get date time
              id: getDateTime
              uses: actions/github-script@v7
              with:
                  script: |
                      return new Date().toLocaleString('zh-Hans-CN');
            - name: Create or update a comment
              uses: ./.github/actions/unique-comment
              env:
                  DATETIME: ${{steps.getDateTime.outputs.result}}
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  uniqueIdentifier: ${{ github.workflow }}
                  body: |
                      **Checking...**

                      ---

                      Commented by Action `${{github.workflow}}`, last updated on ${{github.env.DATETIME}}.

    init:
        name: init
        runs-on: ubuntu-latest
        steps:
            - name: Init repo
              uses: actions/checkout@v4
              with:
                  ref: ${{github.head_ref}}

            # - name: Init node
            #   uses: actions/setup-node@v4
            #   with:
            #       node-version: 20

            # - name: Init pnpm
            #   uses: pnpm/action-setup@v2
            #   with:
            #       version: 8
            #       run_install: false

            # - name: Get pnpm store directory
            #   shell: bash
            #   run: |
            #       echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

            # - name: Setup pnpm cache
            #   uses: actions/cache@v3
            #   with:
            #       path: ${{ env.STORE_PATH }}
            #       key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
            #       restore-keys: |
            #           ${{ runner.os }}-pnpm-store-

            # - name: Install dependencies
            #   run: pnpm install

    eslint:
        name: check eslint
        runs-on: ubuntu-latest
        needs: [init]
        outputs:
            result: ${{ steps.lint.outputs.result }}
        steps:
            - id: lint
              name: Run eslint
              run: |
                  echo "this is eslint" && echo "result=:white_check_mark: eslint result" >> "$GITHUB_OUTPUT"

    typescript:
        name: check typescript
        runs-on: ubuntu-latest
        needs: [init]
        outputs:
            result: ${{ steps.lint.outputs.result }}
        steps:
            - id: lint
              name: Run tsc
              run: |
                  echo "this is typescript" && echo "result=:x: typescript result" >> "$GITHUB_OUTPUT"

    unitTest:
        name: check unit test
        runs-on: ubuntu-latest
        needs: [init]
        outputs:
            result: ${{ steps.lint.outputs.result }}
        steps:
            - id: lint
              name: Run jest
              run: |
                  echo "this is unit test" && echo "result=unit test result" >> "$GITHUB_OUTPUT"

    replyResult:
        name: reply result
        runs-on: ubuntu-latest
        needs: [eslint, typescript, unitTest]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Get date time
              id: getDateTime
              uses: actions/github-script@v7
              with:
                  script: |
                      return new Date().toLocaleString('zh-Hans-CN');

            - name: Create or update a comment
              uses: ./.github/actions/unique-comment
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  uniqueIdentifier: ${{ github.workflow }}
                  body: |
                      ## Eslint Check Result

                      ${{needs.eslint.outputs.result}}

                      ## Typescript Check Result

                      ${{needs.typescript.outputs.result}}

                      ## UnitTest Check Result

                      ${{needs.unitTest.outputs.result}}

                      ---

                      Commented by Action `${{github.workflow}}`, last updated on ${{steps.getDateTime.outputs.result}}.
