name: check pull request
run-name: 'check pull request #${{ github.event.pull_request.number || github.event.issue.number }}'
on:
    pull_request:
        types: [opened, edited, synchronize, reopened]
    # TODO remove next type
    issue_comment:
        types: [created, edited]
permissions:
    issues: read | write | none
    pull_requests: read
jobs:
    init:
        runs-on: ubuntu-latest
        steps:
            - run: echo "hello"
