name: pull_request
on: pull_request
jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo's default branch
              uses: actions/checkout@v3
            - run: echo "i am eslint"
