name: pull_request
on: [pull_request, push]
jobs:
    eslint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repo's default branch
              uses: actions/checkout@v3
            - run: echo "i am eslint1"

    test:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "hello ${{ github.actor }}, branch $GITHUB_REF"
